uktrade/digital-workspace-v2

- config/settings.py
- package-lock.json
- package.json
- requirements.in
- requirements.txt
- Update to Wagtail 2.9
- Update all other Python and Node dependencies across the board
- Fix quote style in `settings.py`
> Dependency updates

- content/models.py
- core/utils.py
- news/models.py
Set last_viewed cookies for news pages and news home page.
> News pages do not have last viewed set

- about_us/models.py
- about_us/templates/about_us/about_us.html
- core/templates/includes/child-links.html
- tools/models.py
- WCM-376 Fix page list for about us and tools
- WCM-377 Add ability to add child pages to about us pages
> WCM-376 and WCM-377 Fix content issues

- peoplefinder/services/image.py
Turns out we needed to transpose the image based on it's the EXIF data.
> PFM-222 Fix some images being rotated after upload

- peoplefinder/management/commands/migrate_legacy.py
- peoplefinder/models.py
This commit also fixes the profile completion query.
> PFM-241 Fix migrating a manager that has no user

- peoplefinder/services/person.py
- peoplefinder/templates/peoplefinder/profile.html
- peoplefinder/views/manager.py
- PFM-248 Fix manager__slug always appearing in audit log
- PFM-249 Fix manager search on profile edit page
- Add manager's full name to the person audit log
- PFM-250 Fix role display with no job title on the profile details page
> Fix multiple bugs

- home/templates/home/home_page.html
- home/util.py
> If tweets not found handle gracefully

- config/settings/base.py
- config/urls.py
> add XML sitemap

- Makefile
- config/settings/base.py
- config/settings/local.py
- core/templates/base.html
- core/templatetags/git_info.py
- core/views.py
- docker-compose.yml
- poetry.lock
- pyproject.toml
* Add git commit, branch and env info to HTML comment via new templatetag
* Improve Sentry integration
* Add release info to sentry client for better error reporting / associating with releases
* Add messages to capture HTTP Errors
* Add Django-extensions (only used on local env and where local.py settings are used)
* remap `make shell` to use `shell_plus`
* remap `runserver` to `runserver_plus`
> Better developer experience

- assets/stylesheets/components/_layout.scss
- assets/stylesheets/components/_peoplefinder.scss
- assets/stylesheets/components/_search_results.scss
- peoplefinder/templates/peoplefinder/components/search-result-person.html
- search/search.py
- search/templates/search/partials/result/teams.html
- search/templates/search/partials/search_filter.html
- search/templates/search/partials/search_filters.html
- search/templates/search/partials/search_results.html
- search/templates/search/partials/search_results_all.html
- search/templates/search/partials/search_results_category.html
- search/templates/search/partials/search_results_single_category.html
- search/templates/search/search_v2.html
- search/templates/search/v2_search_all.html
- search/templatetags/search.py
- search/urls.py
- search/views.py
- almost there
- wip
- wip
- wip
- wip
- wip
- wip
> Sam's changes

- .circleci/config.yml
- Makefile
> Added new requirements up-to-date check

- .github/workflows/dependabot-requirements.yaml
Auto-generates the requirements.txt file when dependabot updates pyproject.toml and poetry.lock
> Auto-fix dependabot requirements suggestions

- .github/workflows/dependabot-requirements.yaml
#373 appears not to result in an action being triggered - perhaps dependabot doesn't `push` code?
> Update action to be triggered by dependabot PRs

- src/extended_search/managers/__init__.py
- src/extended_search/settings.py
- src/extended_search/tests/test_settings.py
- src/search/templates/search/explore.html
- src/search/templates/search/partials/search_results_single_category.html
- src/search/views.py
Can edit boost vars and view subquery boosts in action from the page
> Search improvements: souped-up explore page

- src/peoplefinder/static/peoplefinder/team-select.js
- src/peoplefinder/templates/peoplefinder/profile-edit.html
> People Finder - Small tweaks

- src/peoplefinder/migrations/0109_person_preferred_first_name.py
We don't need to ask Staff SSO for the the First Name as the User is created with the first_name from Staff SSO and it's unlikely that it has changed.
> DWPF-746 first_name migration

- docker-compose.yml
- src/content/migrations/0020_auto_20230717_0949.py
- Fix migration dependencies
- Remove poetry run from docker-compose
> Fix migrations and running locally

- src/extended_search/backends/backend.py
- src/extended_search/index.py
- src/extended_search/managers/__init__.py
- src/extended_search/managers/query_builder.py
- src/extended_search/settings.py
- src/extended_search/tests/test_indexed.py
- src/extended_search/tests/test_indexedfields.py
- src/extended_search/tests/test_managers_init.py
- src/extended_search/tests/test_settings.py
- src/extended_search/tests/test_types.py
- src/extended_search/types.py
- src/peoplefinder/models.py
- src/search/templatetags/search.py
- src/search/views.py
allow querybuilder to access Nested ES fields
refactor missed indexmanager logic that should have been removed previously
> Nested support and field naming consistency

- assets/stylesheets/components/_search_field.scss
- package-lock.json
- package.json
- src/search/search.py
- src/search/templates/search/partials/result/autocomplete_page.html
- src/search/templates/search/partials/search_category_single_tab.html
- src/search/templates/search/partials/search_form.html
- src/search/templates/search/partials/search_results_all.html
- src/search/templates/search/partials/search_results_category.html
- src/search/templatetags/search.py
- src/search/templatetags/search_explore.py
- src/search/urls.py
- src/search/views.py
- Added logic around zero results tabs, so that when no results are present in the tab, redirect.
- Added Logic & UI for autocompletion search functionality via search-form.
> DWPF-784 Typeahead strong match & no results redirect

- src/core/migrations/0005_fix_waffle_truncate_issue.py
added a migration to kill waffle tables causing unmanaged postgres dependencies
> Fix e2e tests

- src/search/templates/search/partials/search_form.html
- src/search/templatetags/search.py
> Turn off bad results

- src/home/models.py
Co-authored-by: Cameron Lamb <cameron.lamb@digital.trade.gov.uk>
Co-authored-by: Marcel Kornblum <marcel.kornblum@digital.trade.gov.uk>
> Fix homepage tweets cache miss

- Dockerfile.test
- src/content/management/commands/create_section_homepages.py
- src/core/templates/menus/main_menu.html
- src/e2e_tests/test_homepage.py
- src/e2e_tests/test_wagtail_admin.py
> Fix the end to end tests

- assets/stylesheets/components/_home.scss
- assets/stylesheets/components/_layout.scss
- assets/stylesheets/govuk-overrides/main.scss
- src/home/templates/home/home_page_new.html
- src/home/templates/home/includes/news_item.html
- src/home/templates/home/includes/news_item_new.html
> Firebreak: Marcel's FE bits for the new HP

- src/core/templates/includes/gtm_datalayer_info.html
> Fix for missing comma in GTM data

- src/content/models.py
- src/core/urls.py
- src/core/views.py
> DWPF-930 Add a content owners report view

- src/content/templates/content/navigation_page.html
> Navigation Page template fix

- src/dw_design_system/dwds/components/navigation_card.html
- src/dw_design_system/dwds/components/navigation_card.py
- **adds get_context function**
- **modifies template vars to match context**
> Add context to navigation card component

- assets/stylesheets/components/_search_results.scss
- src/content/templates/content/navigation_page.html
- src/dw_design_system/dwds/README.md
- src/dw_design_system/dwds/components/cta_card.html
- src/dw_design_system/dwds/components/cta_card.scss
- src/dw_design_system/dwds/components/engagement_card.html
- src/dw_design_system/dwds/components/engagement_card.py
- src/dw_design_system/dwds/components/engagement_card.scss
- src/dw_design_system/dwds/components/extendable/card.html
- src/dw_design_system/dwds/components/extendable/card.scss
- src/dw_design_system/dwds/components/link_list.html
- src/dw_design_system/dwds/components/link_list.scss
- src/dw_design_system/dwds/components/navigation_card.html
- src/dw_design_system/dwds/components/navigation_card.scss
- src/dw_design_system/dwds/styles/layout-custom.scss
- src/dw_design_system/dwds/styles/temporary-base.scss
- src/dw_design_system/dwds/styles/variables.scss
- src/dw_design_system/dwds/stylesheet.scss
- src/feedback/templates/feedback.html
- src/search/templates/search/partials/search_results.html
Made the following updates after a discussion with the team:
- Generalised the card component
- Updated lots of colours
- Fixed engagement card bug that is currently causing 500s on staging
Some screenshots:
> Component updates after team discussion

- src/content/models.py
> DWPF-1743 Filter BlogPosts by live and public

- src/dw_design_system/dwds/components/link_list.scss
- src/dw_design_system/dwds/styles/layout-primitives.scss
> DWPF-1774 Verify Link List works in 2 columns

- Procfile
- src/core/management/commands/update_index_async.py
- src/core/tasks.py
> DWPF-1785 update search index async

- src/core/templates/includes/header.html
> rename header title if new homepage enabled

- src/config/settings/base.py
- src/config/urls.py
- src/dw_design_system/templates/dw_design_system/components.html
- src/dw_design_system/templates/dw_design_system/partials/component.html
- src/dw_design_system/templatetags/dw_design_system.py
- src/dw_design_system/urls.py
- src/dw_design_system/utils.py
- src/dw_design_system/views.py
> A simple Components page

- src/core/templates/dwds_content.html
- src/dw_design_system/dwds/elements/extendable/card.scss
- src/dw_design_system/dwds/styles/temporary-base.scss
Update the background colour for dwds pages so that the cards are visible
> Updates to the DWDS page background colour

- docs/permissions-and-groups/custom-permissions/extended_search.md
- docs/permissions-and-groups/custom-permissions/peoplefinder.md
- docs/permissions-and-groups/groups/country-factsheet-editor.md
- docs/permissions-and-groups/groups/editors.md
- docs/permissions-and-groups/groups/moderators.md
- docs/permissions-and-groups/groups/news-moderators.md
- docs/permissions-and-groups/groups/peoplefinder-beta-testers.md
- docs/permissions-and-groups/groups/person-admin.md
- docs/permissions-and-groups/groups/proposed/feedback-viewer.md
- docs/permissions-and-groups/groups/proposed/navigation-page-admin.md
- docs/permissions-and-groups/groups/proposed/navigation-page-editor.md
- docs/permissions-and-groups/groups/proposed/post-page-admin.md
- docs/permissions-and-groups/groups/proposed/post-page-editor.md
- docs/permissions-and-groups/groups/proposed/search-admin.md
- docs/permissions-and-groups/groups/proposed/search-setting-admin.md
- docs/permissions-and-groups/groups/proposed/tag-admin.md
- docs/permissions-and-groups/groups/proposed/tag-user.md
- docs/permissions-and-groups/groups/site-alert-banner-admin.md
- docs/permissions-and-groups/groups/team-admin.md
- docs/permissions-and-groups/index.md
- mkdocs.yml
> DWPF-1794 Groups and perms docs

- src/dw_design_system/dwds/components/link_list.html
- src/dw_design_system/dwds/components/link_list.scss
- src/dw_design_system/dwds/elements/extendable/card.scss
> INTR-192 Updates to the link list component

- src/dw_design_system/dwds/components/banner_card.html
- src/dw_design_system/dwds/components/banner_card.scss
- src/dw_design_system/dwds/components/cta_card.scss
- src/dw_design_system/dwds/elements/extendable/card.scss
- src/dw_design_system/utils.py
> INTR-193 Update the banner card component

- src/core/templates/base.html
- src/core/templates/includes/footer.html
- src/core/templates/includes/header.html
- src/dw_design_system/dwds/styles/layout.scss
- src/dw_design_system/dwds/styles/variables.scss
> INTR-206 Make page width consistent across app

- src/dw_design_system/dwds/components/engagement_card.html
- src/dw_design_system/dwds/components/engagement_card.scss
- src/dw_design_system/dwds/components/one_up_card.html
- src/dw_design_system/dwds/components/one_up_card.scss
- src/dw_design_system/dwds/elements/extendable/card.html
- src/dw_design_system/dwds/elements/extendable/card.scss
- src/dw_design_system/dwds/styles/typography.scss
- src/interactions/static/interactions/interactions.scss
- src/interactions/templates/interactions/bookmark_card.html
- src/interactions/templates/interactions/bookmark_list.html
> Update bookmark card visuals

- assets/stylesheets/components/_home_new.scss
- src/content/templates/content/navigation_page.html
- src/dw_design_system/dwds/components/engagement_card.html
- src/dw_design_system/dwds/components/engagement_card.py
- src/dw_design_system/dwds/components/one_up_card.html
- src/dw_design_system/dwds/elements/extendable/card.scss
- src/dw_design_system/dwds/styles/layout.scss
- src/dw_design_system/dwds/styles/variables.scss
- src/home/models.py
- src/home/templates/home/home_page_new.html
- src/interactions/templates/interactions/bookmark_card.html
First iteration of the homepage layout.
Further changes to be done:
- Header to be updated.
- Good morning/afternoon text to be added.
- Other design improvements.
> INTR-199 Update homepage layout

- src/content/templates/content/navigation_page.html
- src/core/templates/base.html
- src/dw_design_system/dwds/styles/layout.scss
Make the navigation page the new page width in all scenarios
> Update the site width

- src/dw_design_system/dwds/styles/temporary-base.scss
- src/home/templates/home/home_page_new.html
> Welcome banner temporary removal

- src/dw_design_system/dwds/components/one_up_card.scss
Readjusted the ratio of 1-up card to have more text space and less image space. (This reduces height of the card too)
> INTR-243 Changes to 1-up card

- src/dw_design_system/dwds/components/engagement_card.scss
- src/dw_design_system/dwds/elements/extendable/card.scss
> INTR-232 Update base card <p> margins

- src/dw_design_system/dwds/components/cta_card.scss
- src/dw_design_system/dwds/components/link_list.scss
- src/dw_design_system/dwds/elements/extendable/card.scss
- src/dw_design_system/dwds/elements/navigational_link.scss
- src/dw_design_system/dwds/styles/temporary-base.scss
- src/home/templates/home/includes/home_banner.html
- src/interactions/static/interactions/interactions.scss
- src/interactions/templates/interactions/bookmark_card.html
Refactoring some accessibility states so they are more consistent.
> INTR-242 Accessibility updates on links/cards

- src/content/templates/content/navigation_page.html
- src/dw_design_system/dwds/styles/layout-primitives.scss
- src/feedback/templates/feedback.html
> INTR-256 Update alignment and buttons for "is this page useful" (HR page)

- poetry.lock
> INTR-207 Upgrade django-feedback-govuk

- src/config/settings/base.py
> Sentry healthcheck filtering

- src/home/models.py
Updated Priority pages to require 4 pages
> INTR-276 New Homepage styling

- assets/stylesheets/govuk-overrides/header.scss
> INTR-286 Update the search box styling

- assets/stylesheets/govuk-overrides/header.scss
> INRT-287 Fix image roundness

- docs/permissions-and-groups/groups/events-creators.md
- docs/permissions-and-groups/groups/events-moderators.md
- src/content/management/commands/create_groups.py
> INTR-265 Add events permissions

- src/dw_design_system/dwds/components/one_up_card.html
- src/dw_design_system/dwds/components/one_up_card.scss
- src/home/models.py
- src/home/templates/home/home_page_new.html
> Fixed events being selected twice in priority

- src/content/models.py
- src/dw_design_system/dwds/components/card_group.html
- src/dw_design_system/dwds/components/engagement_card.html
- src/dw_design_system/dwds/components/engagement_card.scss
- src/dw_design_system/dwds/components/one_up_card.html
- src/dw_design_system/dwds/components/one_up_card.scss
- src/dw_design_system/dwds/elements/extendable/card.scss
- src/home/templates/home/home_page_new.html
- src/home/templatetags/cards.py
> INTR-308 Updates to engagement card date

- src/dw_design_system/dwds/components/engagement_card.scss
- src/home/templates/home/home_page_new.html
- src/home/templatetags/cards.py
Shadows were not showing on the new layout cards.
> Fix shadows on cards

- src/events/templates/events/event_page.html
- src/news/templates/news/news_page_new.html
Fix the scaling of images on the news and events page
> Fix image scaling on news/events

- src/home/models.py
Make sure people that can change the home page content are able to publish their changes
> Home page content editors can publish the home page

- src/core/templates/includes/header.html
From `Intranet` to `The Intranet`
> Update the site name in the header

- src/home/models.py
After a discussion with John and some stakeholders, they want to reduce the number of news items on the home page
> INTR-333 Reduce news items on home page from 8 to 4

- src/dw_design_system/dwds/components/card_group.html
- src/dw_design_system/dwds/components/card_group.scss
- src/dw_design_system/dwds/elements/extendable/card.html
- src/dw_design_system/dwds/elements/extendable/card.scss
- src/home/models.py
- src/home/templates/home/home_page_new.html
> INTR-319 Add link to events page

- assets/stylesheets/govuk-overrides/header.scss
- src/core/templates/base.html
- src/core/templates/includes/header_new.html
An interim site header while we wait for the IA work so that we can design/build a better one in the DWDS
> Header tweaks

- src/dw_design_system/dwds/components/card_group.html
- src/dw_design_system/dwds/components/one_up_card.html
- Update the one up card to follow the same card stack logic as all other cards
- Remove the splitting HR from the DBT news panel (Leave the HR above the link)
> Homepage tweaks after review

- src/home/templates/home/home_page_new.html
Put the view all events link behind a flag as we don't want it to show at the moment
> "View all events" link flag

- src/dw_design_system/dwds/elements/ribbon.scss
This came in as a request from John
> Smaller ribbon text

- src/core/templates/base.html
Updated the site title from "Digital Workspace" to "The Intranet".
> INTR-348 HTML Title should be: The Intranet

- src/home/templates/home/home_page.html
> Wrap the site alert in a card for the rounded corners

- src/home/templates/home/home_page.html
> INTR-386 Update to news section title on homepage

- src/dw_design_system/dwds/elements/content_main.scss
> INTR-385 Fix cards with invisible backgrounds

- src/events/templates/events/event_page.html
> INTR-388 Conditional rendering on event location

- src/core/views.py
> Fix sentry usage in django error handling views

- src/events/models.py
- src/events/templates/events/event_page.html
Change template checks for is online or is in person contain the hybrid logic
> Bugfix: Events register button incorrectly showing

- src/dw_design_system/dwds/elements/button.scss
- src/dw_design_system/dwds/form-items/radio.scss
- src/dw_design_system/dwds/styles/variables.scss
- src/dw_design_system/templates/dw_design_system/styles.html
- src/dw_design_system/views.py
> INTR-398 Add profile navigation buttons to dwds styles page

- Procfile
- docker-compose.yml
- poetry.lock
- pyproject.toml
> INTR-409 Replace waitress with granian

- Makefile
> New Makefile command to run granian locally

- src/events/models.py
- src/events/templates/events/events_home.html
Pr to update event listing logic to consider time when sorting past/upcoming events. Also created a new section for ongoing events.
/events
> INTR-442 - Update the event listing page logic

- src/dw_design_system/dwds/components/menu_vertical.html
- src/dw_design_system/dwds/components/menu_vertical.scss
- src/dw_design_system/dwds/styles/variables.scss
Some tweaks to the vertical menu after review with Design
> Vertical menu design tweaks

- src/core/templates/dwds_content.html
- src/dw_design_system/dwds/components/accordion.html
- src/dw_design_system/dwds/components/accordion.js
- src/dw_design_system/dwds/components/accordion.scss
- src/dw_design_system/dwds/elements/button.scss
- src/dw_design_system/dwds/styles/typography.scss
- src/dw_design_system/dwds/styles/variables.scss
- src/dw_design_system/dwds/stylesheet.scss
- src/dw_design_system/templates/dw_design_system/dwds_components.html
- src/dw_design_system/templates/dw_design_system/styles.html
- src/dw_design_system/utils.py
Accordion dwds component - Hide and show the subsections and all sections
> INTR-400: Build accordion dwds component

- src/dw_design_system/dwds/components/accordion.scss
> INTR-400: Using primary button colour for show all section text

- src/dw_design_system/dwds/elements/profile_image.html
Make sure the small class is added in both scenarios
> Fix: the profile image being small when no URL is available

- src/peoplefinder/templates/peoplefinder/profile.html
All buttons now show together at the bottom of the profile
> Move all buttons on the profile to the same area

- src/peoplefinder/templates/peoplefinder/profile.html
> INTR-463 - Removal of shadow from profile contact card'

- src/content/models.py
- src/core/panels.py
- src/country_fact_sheet/models.py
- src/events/models.py
- src/home/models.py
- src/networks/models.py
- src/news/models.py
- src/tools/models.py
- src/working_at_dit/models.py
> INTR-437: Add optional text next to the optional field's header

- .copilot/image_build_run.sh
- docker-compose.yml
- src/manage.py
> Fix builds

- src/peoplefinder/templates/peoplefinder/profile.html
- src/peoplefinder/views/profile.py
> INTR-481 Show profile tabs even when there is no data to show

- src/core/templatetags/sidebar.py
> INTR-471: Return None if no alert found

- src/content/models.py
- src/content/templatetags/formatting.py
- src/content/utils.py
- src/peoplefinder/templates/peoplefinder/components/team-card-new.html
- src/peoplefinder/templates/peoplefinder/includes/team_buttons.html
- Rename "sub team" to "sub-team"
- Team card truncation
> Pre release changes

- src/core/templatetags/sidebar.py
- src/dw_design_system/dwds/elements/bookmark-icon.html
- src/dw_design_system/dwds/elements/bookmark.scss
- src/dw_design_system/dwds/styles/variables.scss
- src/dw_design_system/dwds/stylesheet.scss
- src/interactions/templates/interactions/bookmark_page_input.html
- src/interactions/views.py
> INTR-496: Apply styling for bookmark

- src/dw_design_system/dwds/form-items/radio.scss
> Fix issue with events radios

- .env.example
- README.md
- pyproject.toml
- src/core/management/commands/runserver.py
- src/manage.py
> Use management command to run debugpy

- src/interactions/services/reactions.py
- src/interactions/test/conftest.py
- src/interactions/test/services/test_reactions.py
> INTR-506: create, update and delete reactions for a given page and user

- src/interactions/services/reactions.py
- src/interactions/test/services/test_reactions.py
> INTR-507: Get reactions count for a given page

- src/interactions/services/reactions.py
- src/interactions/test/conftest.py
- src/interactions/test/services/test_reactions.py
> INTR-508: Get reactions count group by type

- src/dw_design_system/dwds/form-items/select.scss
- src/events/filters.py
- src/events/templates/events/includes/listing_header.html
- src/networks/filters.py
- src/networks/models.py
- src/networks/templates/networks/includes/networks_filters.html
- src/networks/templates/networks/networks_home.html
> INTR-515 Network filtering

- src/networks/templates/networks/networks_home.html
> Reorder pagination component on template

- src/interactions/services/reactions.py
- src/interactions/test/services/test_reactions.py
> INTR-509: Get user's reaction for a given page

- src/interactions/services/reactions.py
- src/interactions/test/services/test_reactions.py
> INTR-510: Return flag to indicate user reacted to a page or not

- src/networks/models.py
> Make sure we show all sub pages on a network page

- src/core/templates/tags/sidebar.html
- src/dw_design_system/dwds/components/engagement.html
- src/news/templates/news/news_page.html
- src/working_at_dit/templates/working_at_dit/content_with_related_topics.html
> Sidebar tweaks

- src/core/templates/tags/sidebar/parts/comment.html
- src/core/templates/tags/sidebar/parts/feedback.html
> INTR-529 Focus textarea when comment icon is clicked

- src/core/templates/tags/sidebar/parts/bookmark.html
- src/core/templates/tags/sidebar/parts/comment.html
- src/core/templates/tags/sidebar/sections/primary_page_actions.html
- src/dw_design_system/dwds/layouts/icon_card.html
- src/dw_design_system/dwds/layouts/icon_card.scss
- src/dw_design_system/dwds/stylesheet.scss
> INTR-534 Add icon card styling for sidebar primary page actions

- src/content/models.py
> INTR-530 Separate any HTML tag join with a new line

- src/networks/templates/networks/networks_home.html
> INTR-529 Add message when no networks are present

- src/core/templates/tags/sidebar/parts/bookmark.html
- src/core/templates/tags/sidebar/parts/comment.html
- src/core/templatetags/sidebar.py
- src/dw_design_system/dwds/elements/button.scss
- src/dw_design_system/dwds/elements/content_icon.scss
- src/dw_design_system/dwds/icons/bookmark.html
- src/dw_design_system/dwds/icons/comment.html
- src/dw_design_system/dwds/layouts/icon_card.scss
- src/interactions/static/interactions/interactions.scss
- src/interactions/templates/interactions/bookmark_page_input.html
> Clean up sidebar icons

- src/core/templates/tags/sidebar/parts/bookmark.html
- src/core/templates/tags/sidebar/parts/comment.html
- src/dw_design_system/dwds/components/profile_info.html
- src/dw_design_system/dwds/elements/content_icon.scss
- src/dw_design_system/dwds/icons/arrow-left.html
- src/dw_design_system/dwds/icons/arrow-right.html
- src/dw_design_system/dwds/icons/bookmark.html
- src/dw_design_system/dwds/icons/briefcase.html
- src/dw_design_system/dwds/icons/celebrate.html
- src/dw_design_system/dwds/icons/comment.html
- src/dw_design_system/dwds/icons/dislike.html
- src/dw_design_system/dwds/icons/email.html
- src/dw_design_system/dwds/icons/like.html
- src/dw_design_system/dwds/icons/love.html
- src/dw_design_system/dwds/icons/marker.html
- src/dw_design_system/dwds/icons/phone.html
- src/dw_design_system/dwds/icons/unhappy.html
- src/dw_design_system/dwds/layouts/icon_card.scss
- src/dw_design_system/templates/dw_design_system/dwds_components.html
- src/dw_design_system/templatetags/dwds_icons.py
- src/dw_design_system/utils.py
- src/peoplefinder/templates/peoplefinder/profile.html
> Fix the icon sizing behaviour across the project

- src/peoplefinder/templates/peoplefinder/profile.html
> Stack the profile view page with one column instead of 2

- src/core/templates/dwds_content.html
- src/dw_design_system/dwds/components/cta.html
- src/dw_design_system/dwds/components/cta_button.html
- src/dw_design_system/dwds/components/cta_button.js
- src/dw_design_system/dwds/icons/feedback.html
- src/dw_design_system/dwds/icons/feedback.scss
- src/dw_design_system/dwds/layouts/content_stack.scss
- src/dw_design_system/dwds/stylesheet.scss
> INTR-536 Update the give feedback component to closely match the designs

- src/core/templatetags/sidebar.py
> INTR-550 Use the correct HTTP/HTTPS for the share URL

- src/dw_design_system/dwds/components/copy_text.scss
> INTR-551 Fix the copy button text alignment

- src/networks/models.py
> INTR-556 Fix excerpts on Network child pages

- pyproject.toml
- src/core/templates/includes/gtm_datalayer_info.html
- src/dw_design_system/dwds/components/page_react_button.js
- src/interactions/templates/interactions/reactions.html
- src/interactions/templatetags/reactions.py
- src/news/templates/news/news_page.html
> INTR-539 GTM reactions templatetag

- src/interactions/templatetags/reactions.py
Make sure we are acting with a Page object
> Fix search page

- src/core/templatetags/sidebar.py
> INTR-565 Remove the `SECURE_SSL_REDIRECT` approach

- src/networks/models.py
> INTR-541 Fix promote panels on NetworkHome and Network Page

- .copilot/config.yml
> Update Paketo builder to latest version

- src/dw_design_system/dwds/components/spotlight.html
- src/dw_design_system/dwds/components/spotlight.scss
- src/dw_design_system/dwds/styles/variables.scss
- src/dw_design_system/dwds/stylesheet.scss
- src/dw_design_system/utils.py
> INTR-571: Create the spotlight component

- src/core/flags.py
- src/core/templates/dwds_content.html
- src/core/templates/tags/sidebar/parts/comment.html
- src/core/templatetags/sidebar.py
- src/interactions/templates/interactions/bookmark_page_input.html
- src/interactions/templatetags/bookmarks.py
- src/interactions/views.py
- src/news/templates/news/news_page.html
> INTR-568: Remove new_sidebar and show_reactions flags

- src/dw_design_system/dwds/elements/content_image.html
Increase the resolution we render the image at so that it doesn't get blurry when stretched
> Improve the card image quality

- src/dw_design_system/dwds/components/author.html
- src/dw_design_system/dwds/components/author.scss
- src/dw_design_system/dwds/stylesheet.scss
- src/dw_design_system/utils.py
Testing:
The component should still be styled correctly regardless of whether profile_image_url is passed or not. (link/image)
[/dwds/components/#author](http://localhost:8000/dwds/components/#author)
> INTR-602 - Create the author component

- src/networks/models.py
> Fix: Only show cards of type Network in network group

- poetry.lock
- pyproject.toml
> Update DBT platform helper

- src/core/templates/dwds_content.html
- src/dw_design_system/dwds/components/author.html
- src/dw_design_system/dwds/components/comment.html
- src/dw_design_system/dwds/components/comments.html
- src/dw_design_system/dwds/components/toggle_visibility_button.html
- src/dw_design_system/dwds/components/toggle_visibility_button.js
- src/dw_design_system/utils.py
- src/interactions/services/comments.py
- src/interactions/templatetags/comments.py
- src/news/forms.py
- src/news/templates/news/includes/news_comments.html
> Improve the behaviour and look of the new comments section

- src/core/templatetags/page.py
> Fix: update timestamps on page_author template tag

- src/content/models.py
- src/interactions/services/comments.py
> INTR-630 Fix calculation for comment counter

- src/dw_design_system/dwds/components/comment.html
- src/dw_design_system/dwds/components/comments.html
- src/dw_design_system/dwds/elements/button.scss
- src/dw_design_system/dwds/form-items/textarea.scss
- src/dw_design_system/dwds/styles/variables.scss
- src/dw_design_system/dwds/stylesheet.scss
- src/interactions/services/comments.py
- src/interactions/views.py
- src/news/forms.py
- src/news/templates/news/includes/delete_comment.html
Had a chat with Cheryl and made some tweaks based on the designs and discussion.
> Update the comment styling

- src/content/models.py
Fix comment count annotation to count those with and without parent comments
> Fix comment count annotation

- src/content/models.py
> Fix: comment count bug on engagement card

- src/core/templates/includes/attribution.html
> INTR-644 - Update attribution date formats

- src/interactions/services/comments.py
- src/interactions/views.py
- src/news/templates/news/includes/delete_comment.html
Deleting a comment should no longer reload the page
> INTR-642 - Use htmx to reload comments section on delete

- src/core/templates/tags/sidebar/parts/share.html
- src/dw_design_system/dwds/components/copy_text.html
- src/dw_design_system/dwds/components/modal.scss
- src/dw_design_system/dwds/elements/button.scss
- src/dw_design_system/dwds/elements/content_icon.scss
- src/dw_design_system/dwds/styles/temporary-base.scss
- src/dw_design_system/templates/dw_design_system/dwds_components.html
- src/dw_design_system/templatetags/dwds_icons.py
- src/dw_design_system/utils.py
- src/news/templates/news/includes/delete_comment.html
Share modal:
Delete comment modal:
> Fix modal, button and icon styling with Cheryl

- src/core/templates/includes/page_publishing_information.html
- src/dw_design_system/dwds/components/author.html
- src/dw_design_system/dwds/components/comment.html
- src/dw_design_system/dwds/components/engagement.html
- src/dw_design_system/dwds/elements/page_counts.html
- Date formatting and presentation
- Correct capitalisations
- Comment button ordering
> Lots of changes to content after a chat with Sorcha

- src/dw_design_system/dwds/components/comment.html
- src/dw_design_system/dwds/elements/button.scss
- src/interactions/services/comments.py
A comment without reactions:
A comment with reactions:
> Prevent comment reactions depending on if a page allows reactions

- poetry.lock
- pyproject.toml
> DBT Platform Helper update

- .copilot/config.yml
> Paketo Buildpack update

- src/dw_design_system/dwds/components/quote.html
- src/dw_design_system/utils.py
> Bug fix on dwds components page 

- src/peoplefinder/filters.py
- src/peoplefinder/templates/peoplefinder/discover.html
- src/peoplefinder/templates/peoplefinder/includes/discover_filters.html
- src/peoplefinder/utils.py
- src/peoplefinder/views/directory.py
Added the filter component and city filter to people finder discover view, using `django_filters.ChoiceFilter`
> IDPF-395 Add filter component and city filter to discover view

- src/peoplefinder/templates/peoplefinder/discover.html
- src/peoplefinder/templates/peoplefinder/includes/discover_filters.html
- src/peoplefinder/test/views/test_directory.py
- src/peoplefinder/urls.py
- src/peoplefinder/views/directory.py
Basic pagination implementation using DWDS component
> IDPF-392: PF discover page pagination

- src/core/filters.py
- src/events/filters.py
- src/networks/filters.py
- src/peoplefinder/filters.py
- src/peoplefinder/templates/peoplefinder/discover.html
- src/peoplefinder/views/directory.py
> PF Discover view tweaks

- src/content/templates/content/navigation_page.html
- src/dw_design_system/dwds/layouts/content_stack.scss
- Full width title bar
- Re-order sidebar so bookmarks appear at the top
- Fix navigation link width
> Nav pages updates

- src/extended_search/management/commands/indexed_models_and_fields.json
- src/peoplefinder/models.py
You should now see Person results when searching a users job_title(s)
> INTR-655 - Search job_titles

- src/working_at_dit/templates/working_at_dit/topic.html
> Fix the sidebar on the topic page

- src/dw_design_system/dwds/components/author.html
> Author component - Show either published or updated

- src/peoplefinder/filters.py
- src/peoplefinder/templates/peoplefinder/includes/discover_filters.html
> IDPF-441: Profile completion filter

- src/peoplefinder/filters.py
a step towards the design. easier to use I think - but also veeeery long page for now
> All filters as checkbox sets

- src/peoplefinder/filters.py
- src/peoplefinder/templates/peoplefinder/discover.html
- src/peoplefinder/templates/peoplefinder/includes/discover_filters.html
* "not set" (null) option selectable for all filters
* Labels capitalised and typo fixed
* sort positioned top right
* apply button at the top
> IDPF-427 / IDPF-442: Null option and layout tweaks

- src/dw_design_system/dwds/form-items/select.scss
- src/peoplefinder/filters.py
- src/peoplefinder/templates/peoplefinder/discover.html
- src/peoplefinder/templates/peoplefinder/includes/discover_filters.html
Quick PR for demo, to disable styling on multi-select as multi select does not show 'ticked' boxes when dwds styles are running.
> Fix Multiselect checkbox styles do not work

- src/dw_design_system/dwds/components/profile_info.html
- src/peoplefinder/templates/peoplefinder/discover.html
A bit hacky but I don't think we have a clean way to do this efficiently. Also, I think we'll probably be moving to a new profile card soon so hopefully this is short-lived.
> IDPF-422: Inactive marker on profiles

- src/peoplefinder/filters.py
- src/peoplefinder/services/directory.py
* Sort order dd defaults to "Grade"
* refine dds have an "all" option, which is clearer
> IDPF-446: default sort order and small filter tweaks

- src/core/filters.py
- src/peoplefinder/templates/peoplefinder/includes/discover_filters.html
- src/peoplefinder/views/directory.py
> IDPF-443: Selected filters listed with remove links

- src/content/blocks.py
> INTR-699 Fix person role for the quote and person banner component

- .github/workflows/docs.yml
> Add permissions to workflow

- poetry.lock
> Update tornado to resolve high security vulnerability

- src/home/forms.py
- src/networks/models.py
Home and Network page templates skipped the previous fix
> HOTFIX: add db overload fix to missed page templates

- src/content/templates/content/section_page.html
- src/dw_design_system/dwds/components/section.html
- src/dw_design_system/dwds/layouts/content_grid.scss
- src/dw_design_system/dwds/styles/variables.scss
> INTR-681 - Update SectionPage styling

- src/content/templates/content/section_page.html
We have a new one in the sidebar in any case, and the old one messed with the layout a bit
> Remove old feedback prompt from SectionPage
