uktrade/digital-workspace-v2

config/settings/base.py

It can run expensive queries but presumably only when actually used. Gives content people a link in the document edit page showing them where specific docs are linked to, to make it easier to manage which docs should be live and which can be deleted etc.
https://docs.wagtail.org/en/v2.8.1/reference/settings.html#usage-for-images-documents-and-snippets

Enable Wagtail document usage view

---

config/settings/base.py

The setting doesn't take into account use of assets within RTEs or StreamField, making it pretty useless for us. Since it carries a load cost as well, it's worth reverting.

Revert usage count setting

---

search/search.py
search/test/test_search.py
search/views.py

People entering various non-URL-safe chars break the search function
https://sentry.ci.uktrade.digital/organizations/dit/issues/71022/?project=161
This PR removes those characters from the query silently, allowing for more likely matching. 
It also preserves quoted search phrases, but parses all their contents to remove unsafe chars. Phrases are only recognised if properly quoted inside matching pairs of quotes - either `'` or `"`. These quote marks are preservable because the legacy query building functionality treats them as a special case and processes them accordingly.

WCM-43: add sanitize function for search queries

---

search/templates/search/partials/search_results_all.html
search/templates/search/partials/search_results_category.html
search/templatetags/search.py

sometimes we need the result type for things like "featured guidance pages" or "there are no tools matching your search" UI elements even if we're not showing headings

headings and result types split out for extra uses

---

src/peoplefinder/templates/peoplefinder/partials/profile-completion-field-link.html
src/peoplefinder/templates/peoplefinder/profile.html
src/peoplefinder/templatetags/profile.py

This PR fixes the issue that Nico spotted with the Profile page summary, where it is wrapping a long email.
It's because there is an empty actions div.

Only return the actions markup if the links are being shown

---

src/config/settings/base.py
src/core/middleware.py

https://uktrade.atlassian.net/browse/DWPF-161
Not 100% convinced this is a great idea, though it's definitely nicer user experience for e.g. article published date. Any watch-outs you can think of, perhaps re: infra, logging, etc?

switch settings to en-gb and Europe/London TZ

---

src/e2e_tests/test_peoplefinder.py

Test changes since we use the Preferred name now instead of the "first_name"

DWPF-746 Fix e2e tests

---

src/config/settings/base.py

Currently the original log output is being lost in ASIM format. Most of the output from `django_audit_log_middleware`, for instance, is being lost

set DLFA_INCLUDE_RAW_LOG to True

---

src/core/templates/base.html

We are seeing an influx of errors because the GTM Datalayer code is being used at Wagtail page preview time. And the GTM DL code is trying to get a list of all Topic titles. However, it is failing due to the way that querysets work at preview time.
We could dig a little deeper and fix the code so that it works in this scenario, but it begs the question:
**Should we be pushing to the Datalayer when an editor is previewing a page in the Wagtail admin?**
My initial feeling is that we shouldn't (hence this PR)

Hide GTM datalayer output in preview

---

src/content/models.py

Modelcluster doesn't play well with values_list, so @SamDudley suggested we just do a simple list comprehension.

Convert to list comprehension to appease modelcluster

---

src/dw_design_system/dwds/components/link_list.scss

Override the max inline size for the UL so that we can use all of the space

Update the link list styling to use all of the available space

---

scripts/hawk-api-access-test.py
src/peoplefinder/models.py
src/peoplefinder/views/api/person.py

Updates to the PeopleFinder API endpoint:
- Change `city` value to come from the `uk_office_location` value and falls back to `town_city_or_region`
- Add `uk_office_location` value to the endpoint

DWPF-1859 - Update PF API endpoint

---

src/content/models.py

The better approach here would be to check if the template exists and if not, fallback to the old one.
However we plan on getting rid of this `_new` suffix soon so this approach is ok for now

Simple fix for navigation templates

---

src/interactions/templates/interactions/bookmark_index.html
src/interactions/templates/interactions/bookmark_list.html

Update the remove bookmark buttons to use a different style:

Update the bookmark remove button

---

src/search/search.py

Return the specific page models so we have access to `.excerpt`

Fix the search results to include the excerpt

---

src/dw_design_system/dwds/components/banner_card.scss
src/dw_design_system/dwds/elements/extendable/card.scss
src/dw_design_system/dwds/elements/navigational_link.scss
src/dw_design_system/dwds/styles/temporary-base.scss
src/dw_design_system/dwds/styles/typography.scss
src/dw_design_system/dwds/styles/variables.scss
src/dw_design_system/dwds/unsure/ribbon.scss
src/dw_design_system/templates/dw_design_system/styles.html
src/dw_design_system/views.py

Update headings so that we now have text size variables.
Update the DWDS styles page so that it highlights the basic styling of the new system

DWDS Update text sizing and styles page

---

docker-compose.yml

With the new OSX Sequoia update, requests from within the Docker image can't resolve hostnames.
This aims to fix that issue.

Fix OSX docker DNS settings

---

src/config/settings/base.py
src/core/templates/dwds_content.html
src/dw_design_system/dwds/elements/ribbon.html
src/dw_design_system/dwds/elements/ribbon.js
src/dw_design_system/dwds/elements/ribbon.scss

The ribbon styling is a little odd this PR simplifies the spacer logic.
Issues still remaining:

INTR-332 Fix ribbon styling

---

docker-compose.yml

This change is no longer needed, the issue was caused by a security rule blocking the firewall and this "workaround" just causes more issues in other areas.

Revert DNS change in docker compose

---

src/dw_design_system/dwds/elements/ribbon.scss

Make sure the ribbon is only as wide as it needs to be.
Before:
After:

Fix ribbon width

---

src/core/panels.py
src/core/templates/core/forms/widgets/readonly_page.html
src/core/widgets.py
src/home/models.py

This PR adds a new panel type for selecting a page and preventing the ability to edit the page once it's set. A "Page Selector" instead of a "Page Chooser".
As you can see in the GIF above, the behaviour is as follows:
- Adding a new priority page allows for:
- Selecting a page
- Removing the page
- Choosing a different page
- After saving the page as a draft you can still:
- Selecting a page
- Removing the page
- Choosing a different page
- After publishing a page you can no longer change the page, you have to delete the priority page item and create a new instance

INTR-346 Home priority page order bug

---

assets/stylesheets/govuk-overrides/header.scss

Changed the color of header navigation ancestors to [$govuk-link-visited-colour ](https://design-system.service.gov.uk/styles/colour/).

Changed active ancestor to govuk-link-visited-colour

---

assets/stylesheets/govuk-overrides/header.scss

After reviewing the changes on staging, the styling looked a little odd:
This PR removes all the styling for the ancestor links in the header nav which results in a style that looks more inline:

INTR-340 Remove all references to ancestor styling

---

src/dw_design_system/dwds/components/engagement.html
src/dw_design_system/dwds/layouts/content_grid.scss

Component fixups

---

src/dw_design_system/dwds/components/content_list.scss
src/home/templates/home/home_page.html

I spotted this after reviewing the recent changes on staging:
It might be hard to see, but in the image above, the image has rounded corners. This only happens in the content list when displayed as a grid.
The behaviour is wanted in a content list when displayed as a vertical list:
This PR fixes this issue by resetting the images styling only in the grid scenario:

Cards in a content list grid shouldn't have the rounded corners

---

.tool-versions
poetry.lock
pyproject.toml
src/config/urls.py
src/events/views.py

This is very basic PoC code as a spike. It's not intended for real world use. It's going into the codebase in order that we can have a stable URL for an iCal feed, so that we can connect clients to it and verify that it works as a PoC, with the idea that we eventually write some real code to do it properly.
Currently the `/ical/all` endpoint should return a list of all the events in the system, plus a special "dummy event" that is always set to start 10 minutes from the time the endpoint is accessed. This is so that it's easy from the client side to see when the feed was last accessed; again this is for spike purposes.

INTR-289: Calendar feed endpoint [POC]

---

src/search/templatetags/search.py

This PR is mainly for discussion and possibly a quick win.
Caching the counts for a short period will mean that we don't need to perform multiple queries to Open Search for data that we have already pulled moments ago.
- The all search result page currently performs 15 OS requests
- The Individual category pages perform 9 OS requests
With this caching in place, that should be reduced to:
- The all search result page currently performs 9 OS requests
- The Individual category pages perform 7 OS requests
Locally the improvements are night and day!

Cache search counts

---

src/dw_design_system/dwds/elements/button.scss
src/dw_design_system/dwds/styles/variables.scss

This PR updated the existing dwds button styles to have a thicker border at the bottom as per the designs 
/dwds/styles

INTR-399 Update button styling

---

src/dw_design_system/dwds/styles/variables.scss

PR to fix the button focus styling not turning yellow when clicked
/dwds/styles
Before:
After:

INTR-441 Fix button focus styling

---

src/dw_design_system/utils.py

Add condition so that the page works with no thumbnail image

Fix the DWDS components page to work with no thumbnail

---

src/dw_design_system/dwds/components/link_navigate.html

PR to fix the capitalisation issue of prev/next months on the event listing page.
/events/
Before
After

INTR-443 - Fix the capitalisation of prev/next links on event page

---

src/content/templates/content/navigation_page.html
src/dw_design_system/dwds/utils.scss

Fix the navigation page styling

---

src/peoplefinder/templates/peoplefinder/team.html
src/peoplefinder/views/team.py

After discussion with the team, some changes were requested:
- When showing the percentage as `50` it should not contain any unnecessary zeros, example `50.0%`
- The profile completion should be lower down in the team bio
- I've placed it above the buttons as those will be moving in future work.
**Before**
**After**

Profile completion formatting

---

src/dw_design_system/dwds/components/cta.scss

Fix team card email wrap

---

src/core/templatetags/sidebar.py

The bookmarks sidebar part is returning that it should be visible on pages that are NOT a Wagtail Page.
Before:
After:

Only show bookmark icon on pages

---

src/dw_design_system/dwds/icons/bookmark.html
src/dw_design_system/dwds/icons/bookmark.scss
src/dw_design_system/dwds/icons/comment.html
src/interactions/templates/interactions/bookmark_page_input.html

And invert the colour on hover.

INTR-535 Add dark/light styling to the bookmark icon

---

src/news/models.py
src/news/templates/news/news_page.html

When there is a comment already on the page, the reply form has a field with the same ID as the main comment form.
This PR fixes this issue by adding an auto_id prefix to the comment form so that it's fields don't overlap with the main comment form.

Fix share button when there is a reply form

---

src/core/templatetags/sidebar.py

If the networks hub flag isn't active, don't show useful links

Hide useful links when networks hub flag is inactive

---

src/core/templates/tags/sidebar/parts/spotlight.html
src/dw_design_system/dwds/components/engagement.html
src/dw_design_system/dwds/components/one_up.scss
src/dw_design_system/dwds/components/spotlight.html
src/dw_design_system/dwds/components/spotlight.scss
src/dw_design_system/dwds/elements/content_image.scss

The spotlight component is showing with a white background and no rounded corners.
Before:
After:

Fix spotlight image

---

src/dw_design_system/dwds/components/spotlight.scss
src/dw_design_system/dwds/elements/sidebar_part.scss

The spotlight should now have the correct margin and the sidebar styling should overwrite said margin.

INTR-647 - Spotlight component spacing

---

src/peoplefinder/services/directory.py
src/peoplefinder/templates/peoplefinder/discover.html

Also updated the service to run the annotations for easier access to e.g. job title. We probably want to optimise this but right now it does the job

IDPF-390: add existing people card to Discover view

---

src/core/templatetags/sidebar.py

- I used the `site_alert.html` template for the DiscoverPage template.
- `banner_text`, is set as "New 'discover people' page is available!" (for now).

IDPF-401 Add homepage banner for discover view

---

src/dw_design_system/dwds/layouts/content_stack.scss

When using the variable approach, `.content-stacks` don't obey the spacing provided by a parent `.content-stack`.
**Example:**
The following are inside a `.content-stack.large` but they have just a class of `.content-stack`. This means they should have larger spacing between components, than between the child elements.
As we can see, the spacing between the 2 quote components (with just a `content-stack` class have narrower spacing above than the person banner component which has no `content-stack` class.
Below is the same scenario with the style changes from this PR:
All of the spacing is correct based on the stack the element is in.

Fix the content stack styling as the variable approach isn't working

---

src/core/templates/tags/sidebar/parts/comment.html
src/core/templates/tags/sidebar/parts/feedback.html

When the script tag is the first item in the stack it causes the element after to have margin on the top, but since the script tag is invisible, it results in the sidebar spacing being incorrect

Move the scripts inside the elements so it doesn't impact spacing

---

src/dw_design_system/dwds/components/engagement.html
src/dw_design_system/dwds/components/engagement.scss
src/dw_design_system/dwds/elements/content_image.scss

Fix image resizing in content

---

src/peoplefinder/templates/peoplefinder/team-add-new-subteam.html
src/peoplefinder/views/team.py

When adding a sub team, the parent team wasn't being set correctly, leading to teams being added below the root team.
This PR fixes this bug

INTR-697 Bugfix: Add sub team set initial parent team 

---

src/peoplefinder/views/directory.py

using the render shortcut method skipped the middleware that provides the context to get the profile rendering; switching to TemplateResponse delays the rendering and allows the middleware to run

IDPF-445: Fixed missing profile icon
